### ISSUE TITLE
Feature Request: Italicize text

### ISSUE THREAD

**Issue by seangwright** [ryzngard/Carnation#24]
It would be awesome if we could use italics for syntax in addition to the "bold" option that already exists.

Here's a mockup
![Screenshot 2021-11-09 095852](https://user-images.githubusercontent.com/1382768/140948630-c57ebda1-b827-47fb-a213-b97c754a6b9a.jpg)

**Comment by ryzngard** [comment]
@JoeRobich does vs support this?

**Comment by JoeRobich** [comment]
@ryzngard It is not part of the VS Fonts and Colors configuration info. See the available font flags at https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2008/64ycshb0(v=vs.90)

**Comment by seangwright** [comment]
Hmm... This is available in an extension that doesn't support VS 2022

https://github.com/hicknhack-software/semantic-colorizer/blob/develop/SemanticColorizer/EditorFormats.cs#L46

It looks like that isn't programmatically configurable in that extension, which is unfortunate.

**Comment by ryzngard** [comment]
As designed we're limited to VS configuration for font settings. If we did semantic classification and modified those settings directly in our own classifier we could make it work, but we would be constrained to whatever languages we ship a classifier for.

**Comment by JoeRobich** [comment]
Would likely be better to simply report this as a feature suggestion in VS and upvote similar suggestions on DevCommunity.

![image](https://user-images.githubusercontent.com/611219/141000432-88f3af09-523a-422d-bac5-93763f162afd.png)

**Comment by seangwright** [comment]
Gotcha, that makes sense. I'll go look for an existing request or make a new one for VS.

I like your extension!! It makes the workflow for customizing colors 1000x less painful. Thanks for all the work 🙏
